### ISSUE TITLE
isSameValueZero not described in docs

### ISSUE THREAD

**Issue by Dagur** [planttheidea/micro-memoize#120]
The README describes *isEqual* as

> function(object1: any, object2: any): boolean, defaults to _isSameValueZero_

but doesn't explain what isSameValueZero means.

What I'm curious to know is how it compares objects. Does it do a shallow comparison or just check if it's the same object.

**Comment by planttheidea** [comment]
If you look at the documentation for [isEqual](https://github.com/planttheidea/micro-memoize?tab=readme-ov-file#isequal), there is a note regarding `SameValueZero` that describes it specifically:

> NOTE: The default method tests for [SameValueZero](http://ecma-international.org/ecma-262/7.0/#sec-samevaluezero) equality, which is summarized as strictly equal while also considering NaN equal to NaN.

It also contains a link to the ECMA documentation for `SameValueZero` as a concept, which is a standard part of the language.
