### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by ehmicky** [planttheidea/micro-memoize#22]
Could you please add git tags on new releases? This will automatically create GitHub releases, which can help users getting notified on new releases via RSS.

Thanks for this project!

**Comment by planttheidea** [comment]
I've actually been meaning to transition to using GitHub releases instead of just a changelog file, and this is the impetus I needed to do it retroactively.

I'm traveling right now, but I'll try to take care of that this weekend.

**Comment by ehmicky** [comment]
I personally use [`release-it`](https://github.com/webpro/release-it) and it works like a charm but there are other similar tools as well to automate this task.

**Comment by planttheidea** [comment]
First off, appreciate you pinging on this thread, I had forgotten all about it. Good timing too, I just released version `3.0.0`, and I manually created a github release for that version.

Second, good call on the `release-it` package, I'll definitely be giving that a go with the upcoming v6 release of `moize` (as well as releases of my other packages going forward).

**Comment by planttheidea** [comment]
Just did my first attempt with `release-it`, and works like a charm. Thanks for the recommendation, I'll use it henceforth!
