### ISSUE TITLE
Mixture of deep and shallow arguments

### ISSUE THREAD

**Issue by pentacular** [planttheidea/micro-memoize#39]
I didn't see any obvious way to handle a case like the following.

const foo = (options, a, b) => { ... }

Here, you'd want options to use deep equality, but a and b to compare identities.

Is there any convenient way to do this with micro-memoize?

Thanks.

**Comment by planttheidea** [comment]
Indeed there is! This is one of the use-cases for the `isMatchingKey` option.

```ts
const fn = (options: DeepObject, a: string, b: string) => ({
	...options,
	a,
	b,
});

const memoizedFn = memoize(fn, {
	isMatchingKey(
		[existingOptions, existingA, existingB]: [DeepObject, string, string], 
		[newOptions, newA, newB]: [DeepObject, string, string]
	) {
		return deepEqual(existingOptions, newOptions) && existingA === newA && existingB === newB;
	}
});
```

I'm realizing the documentation for this option is not great, I'll improve it with better examples shortly, but basically `isMatchingKey` will receive two parameters, an existing key in cache and the key for the most recent call, and you can use whatever comparison technique you would like to determine equality between the two keys.

**Comment by pentacular** [comment]
I see, that makes sense -- thanks. :)

**Comment by planttheidea** [comment]
No problem! Any other questions, don't hesitate to ask.
