### ISSUE TITLE
Remove memcache tags

### ISSUE THREAD

**Issue by aikar** [planttheidea/micro-memoize#41]
This library incorrectly defines npm tags for memcache and memcached and should be removed, as I can not find any evidence of an integration to memcache.

It is misleading for people looking for memcache libraries to get this result which solves an entirely different problem.

**Comment by planttheidea** [comment]
Fair, honestly I can't remember why those were added originally. I'll remove them this weekend.

**Comment by planttheidea** [comment]
Resolved with #42 and released as part of `4.0.9`. Sorry for the confusion!
