### ISSUE TITLE
Snapshot results

### ISSUE THREAD

**Issue by cemremengu** [planttheidea/micro-memoize#47]
Is there a way to snapshot results so that memoized output is not affected by changes?

```
const memoize = require('micro-memoize');

const assembleToObject = (one, two) => ({ one, two });

const memoized = memoize(assembleToObject);

console.log(memoized('one', 'two')); 
console.log(memoized('one', 'two')); 
memoized('one', 'two').one = 'changed';
console.log(memoized('one', 'two')); 
```

This prints:

```
{ one: 'one', two: 'two' }
{ one: 'one', two: 'two' }
{ one: 'changed', two: 'two' }
```

I want the code above always return`{ one, two }`

**Comment by planttheidea** [comment]
Memoization is meant to avoid expensive recomputation of a result based on known previous inputs ... What those inputs and outputs are can be anything you want them to be. In your case, you want the output to be immutable, so your code would need to account for this.

There are a number of ways to accomplish this; an example would be to freeze the object returned by `assembleToObject`. Either way, this is not something the library would handle.
