### ISSUE TITLE
Advice on reseting the cache

### ISSUE THREAD

**Issue by Offirmo** [planttheidea/micro-memoize#56]
Hi again and thanks for this amazing lib!

I'm having trouble with my unit tests in which the memoized wrongly share results between unrelated tests 😅. (would not happen in real execution, by design)

The easy solution is to reset the cache between each test with `beforeEach`

However I'm not sure how I should be reseting the cache.

Would this reliably work?

```js
memoized.cache = {
  keys: [[]],
  values: [],
}
```

**Comment by planttheidea** [comment]
It can be even simpler than that! Try this:

```js
memoized.cache.keys.length = 0;
memorized.cache.values.length = 0;
```

This retains the original cache arrays internally but clears them out. I would also recommend clearing in an `afterEach` instead of `beforeEach` to prevent accidentally bleed between `describe` blocks.

**Comment by Offirmo** [comment]
Thanks @planttheidea and good point for `afterEach` 👍
