### ISSUE TITLE
Feature request: set timeout for "cached" values

### ISSUE THREAD

**Issue by Rush** [planttheidea/micro-memoize#89]
Hi there, Looks like a great utility. Would it be possible to add the cache "timeout"? Equivalent of what memoizee has.

**Comment by planttheidea** [comment]
If you want something that is more feature rich, you might consider [`moize`](https://www.npmjs.com/package/moize) which has a [`maxAge`](https://www.npmjs.com/package/moize#maxage) feature to accomplish this. `micro-memoize` is intentionally minimal in implementation, but `moize` uses it under the hood and builds on top of it with a bunch of additional features if you need a more robust solution.

**Comment by Rush** [comment]
Thank you
